import React, { useMemo } from 'react'
import { Card, CardHeader, CardTitle, CardContent } from '../ui/Card'
import {
  MOCK_FORECASTS,
  MOCK_LOCATIONS,
  MOCK_REGIONS,
  MOCK_HISTORICAL_DATA,
  MOCK_ALERTS,
  MOCK_MODEL_METRICS,
} from '../../mock'
import {
  Cpu,
  Layers,
  Database,
  MapPin,
  Calendar,
  AlertTriangle,
  FileCheck,
  HardDrive,
  Activity,
  CheckCircle2,
  Sparkles,
} from 'lucide-react'

export const SystemInfoSection: React.FC = () => {
  // Compute dynamic stats from mock architecture
  const stats = useMemo(() => {
    const dates = MOCK_FORECASTS.map((f) => f.validDate).sort()
    const earliestDate = dates[0] || '2024-07-01'
    const latestDate = dates[dates.length - 1] || '2024-07-20'
    const totalBusts = MOCK_FORECASTS.filter((f) => f.bustStatus === 'bust').length
    const zeroSpreadCount = MOCK_FORECASTS.filter((f) => f.zeroSpread).length

    // Calculate approximate localStorage size
    let storageBytes = 0
    try {
      for (const key in localStorage) {
        if (Object.prototype.hasOwnProperty.call(localStorage, key)) {
          storageBytes += (localStorage[key]?.length || 0) * 2
        }
      }
    } catch {
      storageBytes = 1024
    }

    return {
      totalForecasts: MOCK_FORECASTS.length,
      locationsCount: MOCK_LOCATIONS.length,
      regionsCount: MOCK_REGIONS.length,
      historicalCount: MOCK_HISTORICAL_DATA.length,
      alertsCount: MOCK_ALERTS.length,
      modelsCount: MOCK_MODEL_METRICS.length,
      totalBusts,
      zeroSpreadCount,
      earliestDate,
      latestDate,
      storageKb: (storageBytes / 1024).toFixed(1),
    }
  }, [])

  return (
    <div className="space-y-6">
      {/* Demo Architecture Transparency Notice */}
      <div className="p-4 rounded-xl bg-gradient-to-r from-sky-950/60 via-[#0b172a] to-cyan-950/40 border border-sky-500/30 shadow-lg">
        <div className="flex items-start gap-3.5">
          <div className="w-9 h-9 rounded-xl bg-sky-500/20 text-sky-400 flex items-center justify-center shrink-0 mt-0.5 border border-sky-500/40">
            <Sparkles className="w-5 h-5" />
          </div>
          <div className="space-y-1.5">
            <div className="flex items-center gap-2 flex-wrap">
              <h3 className="text-sm font-bold text-white tracking-tight">
                Standalone Mock Architecture &amp; Data Transparency
              </h3>
              <span className="px-2 py-0.5 rounded-full bg-emerald-500/15 border border-emerald-500/30 text-emerald-300 text-[10px] font-mono font-semibold">
                Autonomous Demo Mode
              </span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              This Weather Intelligence frontend operates entirely as a self-contained, high-fidelity application. All meteorological forecasts, ensemble dispersions, ground-truth observations, and bust alerts are generated by a deterministic in-memory mock architecture representing the Indian Monsoon 2024 season. No live external API keys or remote cloud backend connections are required.
            </p>
          </div>
        </div>
      </div>

      {/* Platform & Build Metadata Card */}
      <Card className="bg-[#0b172a] border-[#1a2e4c]">
        <CardHeader className="border-b border-[#1a2e4c]/60 pb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-sky-500/15 text-sky-400 flex items-center justify-center">
              <Cpu className="w-4 h-4" />
            </div>
            <div>
              <CardTitle className="text-sm font-semibold text-white">
                Platform Specification &amp; Build Metadata
              </CardTitle>
              <p className="text-xs text-slate-400 mt-0.5">
                Runtime configuration, framework versions, and UI execution target.
              </p>
            </div>
          </div>
        </CardHeader>

        <CardContent className="pt-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3.5">
            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="text-[11px] text-slate-400">Application Name</div>
              <div className="text-xs font-semibold text-white mt-1">
                Weather Intelligence Platform
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Bust Detection &amp; Risk System</div>
            </div>

            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="text-[11px] text-slate-400">Software Stage</div>
              <div className="text-xs font-semibold text-sky-400 mt-1">
                Stage 16 — Responsive + UX Polish
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Production Intelligence Suite</div>
            </div>

            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="text-[11px] text-slate-400">Application Version</div>
              <div className="text-xs font-semibold font-mono text-emerald-400 mt-1">
                v1.16.0-standalone
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Production Client Bundle</div>
            </div>

            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="text-[11px] text-slate-400">Engine Health</div>
              <div className="text-xs font-semibold text-emerald-400 mt-1 flex items-center gap-1.5">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                <span>100% Operational</span>
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Client-side Reactive Dispatch</div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Dynamic Mock Data Architecture Statistics */}
      <Card className="bg-[#0b172a] border-[#1a2e4c]">
        <CardHeader className="border-b border-[#1a2e4c]/60 pb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-indigo-500/15 text-indigo-400 flex items-center justify-center">
              <Layers className="w-4 h-4" />
            </div>
            <div>
              <CardTitle className="text-sm font-semibold text-white">
                Live Dynamic Mock Dataset Metrics
              </CardTitle>
              <p className="text-xs text-slate-400 mt-0.5">
                Metrics dynamically computed from the centralized meteorological mock store.
              </p>
            </div>
          </div>
        </CardHeader>

        <CardContent className="pt-4">
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-3.5">
            {/* Total Forecasts */}
            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="flex items-center gap-1.5 text-[11px] text-slate-400">
                <Database className="w-3.5 h-3.5 text-sky-400" />
                <span>Total Forecasts</span>
              </div>
              <div className="text-xl font-bold font-mono text-white mt-1">
                {stats.totalForecasts.toLocaleString()}
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Multi-lead records</div>
            </div>

            {/* Stations Covered */}
            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="flex items-center gap-1.5 text-[11px] text-slate-400">
                <MapPin className="w-3.5 h-3.5 text-emerald-400" />
                <span>Surface Stations</span>
              </div>
              <div className="text-xl font-bold font-mono text-white mt-1">
                {stats.locationsCount}
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Across {stats.regionsCount} Regions</div>
            </div>

            {/* Forecast Lead Horizon */}
            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="flex items-center gap-1.5 text-[11px] text-slate-400">
                <Calendar className="w-3.5 h-3.5 text-amber-400" />
                <span>Lead Horizon</span>
              </div>
              <div className="text-xl font-bold font-mono text-white mt-1">
                1–10 Days
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">+24h to +240h Forecasts</div>
            </div>

            {/* Historical Verification Records */}
            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="flex items-center gap-1.5 text-[11px] text-slate-400">
                <FileCheck className="w-3.5 h-3.5 text-cyan-400" />
                <span>Historical Records</span>
              </div>
              <div className="text-xl font-bold font-mono text-white mt-1">
                {stats.historicalCount.toLocaleString()}
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Multi-year seasonal stats</div>
            </div>

            {/* Active System Alerts */}
            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="flex items-center gap-1.5 text-[11px] text-slate-400">
                <AlertTriangle className="w-3.5 h-3.5 text-rose-400" />
                <span>Generated Alerts</span>
              </div>
              <div className="text-xl font-bold font-mono text-rose-400 mt-1">
                {stats.alertsCount}
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Operational warning notices</div>
            </div>

            {/* ML Models Evaluated */}
            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="flex items-center gap-1.5 text-[11px] text-slate-400">
                <Cpu className="w-3.5 h-3.5 text-purple-400" />
                <span>ML Model Baselines</span>
              </div>
              <div className="text-xl font-bold font-mono text-purple-300 mt-1">
                {stats.modelsCount}
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Evaluated architectures</div>
            </div>

            {/* Temporal Span */}
            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="flex items-center gap-1.5 text-[11px] text-slate-400">
                <Calendar className="w-3.5 h-3.5 text-sky-400" />
                <span>Monitored Period</span>
              </div>
              <div className="text-xs font-bold font-mono text-slate-200 mt-1">
                {stats.earliestDate} to {stats.latestDate}
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Active Monsoon Season</div>
            </div>

            {/* Ensemble Resolution */}
            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="flex items-center gap-1.5 text-[11px] text-slate-400">
                <Layers className="w-3.5 h-3.5 text-emerald-400" />
                <span>Ensemble Members</span>
              </div>
              <div className="text-xl font-bold font-mono text-emerald-400 mt-1">
                50 Members
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Probabilistic dispersion</div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Diagnostics & Client Storage */}
      <Card className="bg-[#0b172a] border-[#1a2e4c]">
        <CardHeader className="border-b border-[#1a2e4c]/60 pb-4">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-teal-500/15 text-teal-400 flex items-center justify-center">
              <HardDrive className="w-4 h-4" />
            </div>
            <div>
              <CardTitle className="text-sm font-semibold text-white">
                Client-Side Runtime &amp; Storage Footprint
              </CardTitle>
              <p className="text-xs text-slate-400 mt-0.5">
                Local storage utilization and client browser telemetry.
              </p>
            </div>
          </div>
        </CardHeader>

        <CardContent className="pt-4">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3.5">
            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="text-[11px] text-slate-400">Settings Store Key</div>
              <div className="text-xs font-mono text-sky-300 mt-1">
                weather_intelligence_settings_v1
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Persistent across browser sessions</div>
            </div>

            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="text-[11px] text-slate-400">LocalStorage Utilized</div>
              <div className="text-xs font-mono text-emerald-400 mt-1">
                ~{stats.storageKb} KB consumed
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Of ~5–10 MB standard quota</div>
            </div>

            <div className="p-3.5 rounded-xl bg-[#060d19] border border-[#1a2e4c]">
              <div className="text-[11px] text-slate-400">Simulated UI Latency</div>
              <div className="text-xs font-mono text-cyan-300 mt-1 flex items-center gap-1.5">
                <Activity className="w-3.5 h-3.5 text-cyan-400" />
                <span>&lt; 10 ms (Zero Network Overhead)</span>
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Synchronous in-memory pipeline</div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
